import React from 'react'
import Searchbar from '../components/Searchbar'
import ImageCard from '../components/ImageCard'
const Home = () => {
    const item = {
        photo: "https://letsenhance.io/static/8f5e523ee6b2479e26ecc91b9c25261e/1015f/MainAfter.jpg",
        author: "",
        prompt: ""
    }
  return (
    <div>
      <h1>Explore popular post in this community</h1>
      <span>generated by ai</span>
      <Searchbar/>

      <div>
        Wrapper
            <div>
                <ImageCard item={item}/>
            </div>
        </div>
    </div>
  )
}

export default Home
